if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'AFFLUENCEGRADE'
'CAMPAIGNVIEWEDEMAIL'
'DAYCAREPRODUCTS'
'NIGHTREPAIRPRODUCTS'
'PREVIOUSCAMPAIGN'
'REP_AGE'
'REP_GENDER'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg5: Rejected using stepwise selection";
end;
end;
