if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'AFFLUENCEGRADE'
'CAMPAIGNVIEWEDEMAIL'
'CLEANSERPRODUCTS'
'DAYCAREPRODUCTS'
'FACEBOOKLIKE'
'LOTIONPRODUCTS'
'LOYALTYCLASS'
'MOBILEAPPLICATIONS'
'NIGHTREPAIRPRODUCTS'
'PREVIOUSCAMPAIGN'
'REP_ADVERTISEMENTZONE'
'REP_AGE'
'REP_CLUSTERGROUP'
'REP_GENDER'
'REP_LOYALTYTIME'
'REP_REGION'
'TIMESINCELASTPURCHASE'
'TOTALSPEND'
) then ROLE='INPUT';
else delete;
end;
