*;
*CONSTANT VALUE;
*;
length IMP_DemClusterGroup $1;
label IMP_DemClusterGroup = 'Imputed: Neighborhood Cluster-7 Level';
IMP_DemClusterGroup = DemClusterGroup;
if DemClusterGroup = '' then IMP_DemClusterGroup = 'U';
length IMP_DemGender $1;
label IMP_DemGender = 'Imputed: Gender';
IMP_DemGender = DemGender;
if DemGender = '' then IMP_DemGender = 'U';
length IMP_DemReg $10;
label IMP_DemReg = 'Imputed: Geographic Region';
IMP_DemReg = DemReg;
if DemReg = '' then IMP_DemReg = 'U';
length IMP_DemTVReg $12;
label IMP_DemTVReg = 'Imputed: Television Region';
IMP_DemTVReg = DemTVReg;
if DemTVReg = '' then IMP_DemTVReg = 'U';
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_DemAffl = 'Imputed: Affluence Grade';
length IMP_DemAffl 8;
IMP_DemAffl = DemAffl;
if missing(DemAffl) then IMP_DemAffl = 8.7030320204;
label IMP_DemAge = 'Imputed: Age';
length IMP_DemAge 8;
IMP_DemAge = DemAge;
if missing(DemAge) then IMP_DemAge = 53.892095358;
label IMP_PromTime = 'Imputed: Loyalty Card Tenure';
length IMP_PromTime 8;
IMP_PromTime = PromTime;
if missing(PromTime) then IMP_PromTime = 6.5710641399;
